Repository hashgreen/hoogii-wallet, pull requests merged in 2022-12, with the labels that each got.

#14 Feature/error message
  package.json
  src/App.tsx
  src/api/api.ts
  src/index.tsx
  src/store/AssetsStore.ts
  src/utils/errorMessage.ts
  yarn.lock
Labels: feat

#13 feat : refine the close icon to back icon, and update setting style
  public/images/icons/back.svg
  public/locales/en/translation.json
  src/container/Settings/index.tsx
  src/layouts/ClosablePage.tsx
Labels: feat

#15 Feature/error message popup
  src/api/api.ts
  src/container/Transfer/TransferPopup.tsx
  src/store/TransactionStore.ts
  src/types/api.ts
  src/utils/CAT.ts
  src/utils/Wallet.ts
  src/utils/errorMessage.ts
Labels: feat

#17 fix: tab title name
  public/favicon.ico
  public/icon128.png
  public/icon16.png
  public/icon48.png
  tabs.html
Labels: fix

#19 fix : remove memo if no need
  src/store/TransactionStore.ts
  src/utils/Wallet.ts
Labels: fix

#18 Fix/main asset usd
  src/container/Home/index.tsx
  src/store/AssetsStore.ts
  src/utils/Wallet.ts
Labels: fix

#20 Feature/implement interface UI
  popup.html
  src/api/extension/messaging.ts
  src/components/HaloImg.tsx
  src/container/Status/WelcomeBack.tsx
  src/popup/index.tsx
  src/popup/pages/locked.tsx
  src/popup/pages/refuse.tsx
Labels: feat

#22 fix: fix exchange rate
  src/container/Home/index.tsx
  src/store/TransactionStore.ts
  src/utils/CAT.ts
Labels: fix

#23 Feature/chain switch
  README.md
  package.json
  src/api/api.ts
  src/container/ImportCAT/ImportCAT.tsx
  src/container/ImportCAT/components/CustomPage.tsx
  src/container/Network.tsx
  src/container/Settings/AddressBook/add.tsx
  src/container/Settings/AddressBook/detail.tsx
  src/container/Settings/AddressBook/edit.tsx
  src/container/Settings/ConnectedSites.tsx
  src/db/index.ts
  src/db/migrations.ts
  src/db/utils.ts
  src/layouts/Header.tsx
  src/popup/pages/enable.tsx
  src/router/index.tsx
  src/store/AssetsStore.ts
  src/store/ConnectedSitesStore.ts
  src/store/DevelopmentStore.ts
  src/store/MnemonicStore.ts
  src/store/WalletStore.ts
  src/store/index.ts
  src/types/chia.ts
  src/utils/constants.ts
  src/utils/extension/storage.ts
  src/utils/storage.ts
Labels: chore, feat

#28 Feature/remove paste tooltip
  public/images/icons/blue-info.svg
  src/components/Mnemonic.tsx
  src/index.css
  src/tabs/pages/mnemonic/importMnemonic.tsx
  tailwind.config.js
Labels: feat

#27 feat: Set mainnet as default network
  src/api/api.ts
  src/store/AssetsStore.ts
  src/store/WalletStore.ts
  src/store/index.ts
  src/utils/extension/index.ts
Labels: feat

#26 fix: fix qa issue
  src/components/Popup.tsx
  src/container/Settings/index.tsx
  src/container/Transfer/components/AssetCombobox.tsx
Labels: fix

#30 Fix/import token issue
  config/defaultCATs.json
  public/locales/en/translation.json
  src/api/api.ts
  src/container/Home/index.tsx
  src/index.css
  src/store/AssetsStore.ts
  src/store/TransactionStore.ts
  src/store/WalletStore.ts
  src/types/chia.ts
  src/utils/constants.ts
  tailwind.config.js
Labels: fix

#32 feat: add stably ramp link from home page and fix tranfer bug
  public/locales/en/translation.json
  src/container/Home/index.tsx
  src/index.css
  src/store/TransactionStore.ts
  src/store/WalletStore.ts
  src/types/chia.ts
  src/utils/constants.ts
  tailwind.config.js
Labels: fix, feat
