Repository hashgreen/hoogii-wallet, pull requests merged in 2023-02, with the labels that each got.

#90 feat: show connect sites page
  src/container/Settings/index.tsx
  src/router/index.tsx
Labels: feat

#92 Refactor/use mojo coin spend
  src/store/TransactionStore.ts
  src/test/StandardTransaction/StandardTransaction.test.ts
  src/utils/CAT.ts
  src/utils/Wallet/Wallet.ts
  src/utils/Wallet/types.ts
  src/utils/storage.ts
Labels: enhancement

#96 Fix/send bigint bug
  src/container/Transfer/TransferPopup.tsx
  src/store/TransactionStore.ts
  src/utils/CAT.ts
  src/utils/SpendBundle.ts
  src/utils/Wallet/Wallet.ts
Labels: fix

#94 Fix/asset icon error defualt image
  src/components/AssetIcon.tsx
  src/utils/CoinSelect/accumulative.ts
  src/utils/CoinSelect/blackjack.ts
Labels: fix

#97 Fix/connected site bug
  package.json
  src/components/Item.tsx
  src/container/Settings/ConnectedSites.tsx
Labels: fix

#98 feat: add isUnlocked function
  src/api/extension/webpage.ts
  src/injected-scripts/index.ts
  src/types/content-scripts.d.ts
Labels: feat

#99 fix: wallet coinSelect bigInt issue
  src/store/TransactionStore.ts
  src/utils/Wallet/Wallet.ts
Labels: fix

#93 Refactor/mnemonic
  package.json
  src/components/Mnemonic.tsx
  src/store/MnemonicStore.ts
  src/store/TransactionStore.ts
  src/tabs/pages/mnemonic/createMnemonic.tsx
  src/tabs/pages/mnemonic/displayMnemonic.tsx
  src/tabs/pages/mnemonic/importMnemonic.tsx
  src/tabs/pages/mnemonic/index.ts
  src/tabs/pages/password.tsx
  src/tabs/pages/policy.tsx
  src/tabs/router.tsx
  src/test/StandardTransaction/StandardTransaction.test.ts
  src/utils/constants.ts
Labels: enhancement

#101 Fix/connect site UI
  package.json
  src/container/Settings/ConnectedSites.tsx
  src/layouts/Account.tsx
  src/popup/controller.ts
  src/popup/pages/refuse.tsx
Labels: fix

#100 Refactor/codebase
  src/api/api.ts
  src/api/extension/request.ts
  src/components/Logo.tsx
  src/components/NeonText/NeonText.tsx
  src/container/Network.tsx
  src/layouts/Header.tsx
  src/layouts/PublicRoute.tsx
  src/popup/pages/switchChain.tsx
  src/router/index.tsx
  src/store/AssetsStore.ts
  src/store/TransactionStore.ts
  src/store/WalletStore.ts
  src/test/StandardTransaction/StandardTransaction.test.ts
  src/types/chia.ts
  src/utils/CAT.ts
  src/utils/Wallet/Wallet.ts
  src/utils/constants.ts
  src/utils/extension/index.ts
  src/utils/storage.ts
Labels: enhancement

#102 Fix/get balance bug
  src/router/index.tsx
  src/store/AssetsStore.ts
  src/utils/CAT.ts
Labels: fix

#104 fix: fix mnemonic issue
  src/store/MnemonicStore.ts
  src/tabs/pages/mnemonic/createMnemonic.tsx
Labels: fix

#105 fix: update groupby logic
  src/components/Transaction/type.ts
  src/container/History/HistoryStore.ts
  src/container/History/index.tsx
Labels: fix

#107 fix: create bug
  src/store/MnemonicStore.ts
Labels: fix

#89 Feature/create offer interface
  package.json
  popup.html
  src/api/extension/permission.ts
  src/api/extension/request.ts
  src/background/index.ts
  src/container/Transfer/TransferPopup.tsx
  src/index.scss
  src/layouts/PublicRoute.tsx
  src/popup/index.tsx
  src/popup/layout.tsx
  src/popup/pages/connecting.tsx
  src/popup/pages/refuse.tsx
  src/popup/pages/switchChain.tsx
  src/popup/pages/transaction.tsx
  src/store/TransactionStore.ts
  src/test/Offer/makeOffer.ts
  src/types/extension.ts
  src/utils/Announcement.ts
  src/utils/CAT.ts
  src/utils/Offer.ts
  src/utils/Secure.ts
  src/utils/Wallet/Wallet.ts
  src/utils/Wallet/types.ts
  src/utils/puzzles.ts
  src/utils/puzzles/cat_old.clvm.hex.json
  src/utils/puzzles/nft_metadata_updater_default.clvm.hex.json
  src/utils/puzzles/nft_ownership_layer.clvm.hex.json
  src/utils/puzzles/nft_ownership_transfer_program_one_way_claim_with_royalties.clvm.hex.json
  src/utils/puzzles/nft_state_layer.clvm.hex.json
  src/utils/puzzles/settlement_payments.clvm.hex.json
  src/utils/puzzles/settlement_payments_old.clvm.hex.json
  src/utils/puzzles/singleton_top_layer_v1_1.clvm.hex.json
  yarn.lock
Labels: feat

#111 Feature/tooltips expend implement
  package.json
  src/components/Transaction/MemoDisplay.tsx
  src/components/Transaction/Transaction.tsx
  src/container/History/index.tsx
  src/index.scss
  src/index.tsx
  src/utils/CAT.ts
  yarn.lock
Labels: feat

#112 Feature/develop mode
  src/components/Version.tsx
  src/container/Network.tsx
  src/container/Settings/index.tsx
  src/types/chia.ts
  src/utils/constants.ts
Labels: feat

#114 Fix/xch display issue
  package.json
  src/App.tsx
  src/store/AssetsStore.ts
Labels: fix
