Repository hashgreen/hoogii-wallet, pull requests merged in 2023-03, with the labels that each got.

#118 Feature/get public keys interface
  src/api/api.ts
  src/api/extension/request.ts
  src/index.scss
  src/popup/components/spendBundleInfo.tsx
  src/types/api.ts
  src/types/extension.ts
Labels: feat

#120 Fix/get public key interface
  src/api/extension/request.ts
  src/api/ga.ts
  src/container/Transfer/TransferPopup.tsx
  src/popup/pages/transaction.tsx
  src/utils/signature.ts
Labels: fix

#122 Fix/transfer send xch issue
  package.json
  src/popup/components/offerInfo.tsx
  src/popup/components/spendBundleInfo.tsx
  src/popup/components/transferInfo.tsx
  src/popup/pages/transaction.tsx
  src/utils/CoinConverter.ts
Labels: fix

#121 Feature/ga issues
  package.json
  src/App.tsx
  src/api/ga.ts
  src/components/CopyTooltip.tsx
  src/components/Transaction/MemoDisplay.tsx
  src/components/Transaction/Transaction.tsx
  src/container/History/index.tsx
  src/container/Home/Info.tsx
  src/container/Home/index.tsx
  src/container/ImportCAT/ImportCAT.tsx
  src/container/ImportCAT/components/CustomPage.tsx
  src/container/Network.tsx
  src/container/Settings/AddressBook/index.tsx
  src/container/Settings/Advance/index.tsx
  src/container/Status/WelcomeBack.tsx
  src/container/Transfer/Transfer.tsx
  src/layouts/Header.tsx
  src/popup/pages/refuse.tsx
  src/types/ga.ts
Labels: feat

#124 refactor: add memo in value
  package.json
  src/container/Transfer/Transfer.tsx
  src/utils/CAT.ts
  src/utils/Offer.ts
  src/utils/Wallet/Wallet.ts
Labels: enhancement, feat

#126 Feat/transfer blance check
  public/locales/en/translation.json
  src/components/ErrorMessage.tsx
  src/container/Transfer/Transfer.tsx
  src/index.scss
  src/store/AssetsStore.ts
Labels: feat

#127 Feature/interface get balance
  src/api/extension/request.ts
  src/components/Transaction/MemoDisplay.tsx
  src/index.scss
Labels: feat

#128 Feature/notification pop up
  package.json
  public/data/reward.json
  public/data/version.json
  public/images/icons/tx-status-reward.svg
  public/locales/en/translation.json
  src/components/Notification.tsx
  src/container/Home/index.tsx
  src/index.scss
  src/types/notification.ts
  src/types/version.d.ts
  tailwind.config.js
  vite.config.ts
  yarn.lock
Labels: feat

#129 Feat/selected token UI
  package.json
  public/data/version.json
  public/images/icons/close-rounded.svg
  src/components/Item.tsx
  src/components/List.tsx
  src/components/Notification.tsx
  src/container/ImportCAT/ImportCAT.tsx
  vite.config.ts
Labels: feat

#131 fix: default token for testnet and mainnet
  config/defaultCATs.json
  src/api/api.ts
  src/router/index.tsx
  src/store/AssetsStore.ts
Labels: fix

#130 Feat/multiple lang
  public/locales/en/translation.json
  public/locales/zh-ch/translation.json
  public/locales/zh-tw/translation.json
  src/container/History/index.tsx
  src/container/ImportCAT/ImportCAT.tsx
  src/container/ImportCAT/components/CustomPage.tsx
  src/container/Network.tsx
  src/container/Settings/Advance/feedback.tsx
  src/container/Settings/Advance/index.tsx
  src/container/Settings/index.tsx
  src/layouts/ClosablePage.tsx
  src/layouts/Header.tsx
  src/popup/components/offerInfo.tsx
  src/popup/components/spendBundleInfo.tsx
  src/popup/components/transferInfo.tsx
  src/popup/pages/connecting.tsx
  src/popup/pages/refuse.tsx
  src/popup/pages/switchChain.tsx
  src/popup/pages/transaction.tsx
  src/types/i18n.ts
  src/utils/i18n.ts
Labels: feat

#132 Feat/detect and alert existed token
  public/images/icons/checked-rounded.svg
  public/locales/en/translation.json
  public/locales/zh-ch/translation.json
  public/locales/zh-tw/translation.json
  src/api/ga.ts
  src/components/List.tsx
  src/container/ImportCAT/components/CustomPage.tsx
Labels: feat

#134 fix: `~` to solve icon catch
  src/api/extension/messaging.ts
Labels: fix

#135 fix: fix import btn disable when paste the code
  src/container/ImportCAT/components/CustomPage.tsx
Labels: fix
